using Microsoft.EntityFrameworkCore.Migrations;

namespace TheBattleApi.Data.Migrations
{
    public partial class RemovingSomeAutoGeneratedColumns : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Ships_ShipGroups_ShipGroupUserId_ShipGroupRoomId_ShipGroupShipTypeId",
                table: "Ships");

            migrationBuilder.DropForeignKey(
                name: "FK_Weapons_WeaponGroups_WeaponGroupUserId_WeaponGroupRoomId_WeaponGroupWeaponTypeId",
                table: "Weapons");

            migrationBuilder.DropIndex(
                name: "IX_Weapons_WeaponGroupUserId_WeaponGroupRoomId_WeaponGroupWeaponTypeId",
                table: "Weapons");

            migrationBuilder.DropIndex(
                name: "IX_Ships_ShipGroupUserId_ShipGroupRoomId_ShipGroupShipTypeId",
                table: "Ships");

            migrationBuilder.DropColumn(
                name: "WeaponGroupRoomId",
                table: "Weapons");

            migrationBuilder.DropColumn(
                name: "WeaponGroupUserId",
                table: "Weapons");

            migrationBuilder.DropColumn(
                name: "WeaponGroupWeaponTypeId",
                table: "Weapons");

            migrationBuilder.DropColumn(
                name: "ShipGroupRoomId",
                table: "Ships");

            migrationBuilder.DropColumn(
                name: "ShipGroupShipTypeId",
                table: "Ships");

            migrationBuilder.DropColumn(
                name: "ShipGroupUserId",
                table: "Ships");

            migrationBuilder.AlterColumn<string>(
                name: "UserId",
                table: "Weapons",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(max)",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "RoomId",
                table: "Weapons",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(max)",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "UserId",
                table: "Ships",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(max)",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "RoomId",
                table: "Ships",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(max)",
                oldNullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_Weapons_UserId_RoomId_WeaponTypeId",
                table: "Weapons",
                columns: new[] { "UserId", "RoomId", "WeaponTypeId" });

            migrationBuilder.CreateIndex(
                name: "IX_Ships_UserId_RoomId_ShipTypeId",
                table: "Ships",
                columns: new[] { "UserId", "RoomId", "ShipTypeId" });

            migrationBuilder.AddForeignKey(
                name: "fk_ship_group",
                table: "Ships",
                columns: new[] { "UserId", "RoomId", "ShipTypeId" },
                principalTable: "ShipGroups",
                principalColumns: new[] { "UserId", "RoomId", "ShipTypeId" },
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "fk_weapon_group",
                table: "Weapons",
                columns: new[] { "UserId", "RoomId", "WeaponTypeId" },
                principalTable: "WeaponGroups",
                principalColumns: new[] { "UserId", "RoomId", "WeaponTypeId" },
                onDelete: ReferentialAction.Restrict);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_ship_group",
                table: "Ships");

            migrationBuilder.DropForeignKey(
                name: "fk_weapon_group",
                table: "Weapons");

            migrationBuilder.DropIndex(
                name: "IX_Weapons_UserId_RoomId_WeaponTypeId",
                table: "Weapons");

            migrationBuilder.DropIndex(
                name: "IX_Ships_UserId_RoomId_ShipTypeId",
                table: "Ships");

            migrationBuilder.AlterColumn<string>(
                name: "UserId",
                table: "Weapons",
                type: "nvarchar(max)",
                nullable: true,
                oldClrType: typeof(string),
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "RoomId",
                table: "Weapons",
                type: "nvarchar(max)",
                nullable: true,
                oldClrType: typeof(string),
                oldNullable: true);

            migrationBuilder.AddColumn<string>(
                name: "WeaponGroupRoomId",
                table: "Weapons",
                type: "nvarchar(450)",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "WeaponGroupUserId",
                table: "Weapons",
                type: "nvarchar(450)",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "WeaponGroupWeaponTypeId",
                table: "Weapons",
                type: "int",
                nullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "UserId",
                table: "Ships",
                type: "nvarchar(max)",
                nullable: true,
                oldClrType: typeof(string),
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "RoomId",
                table: "Ships",
                type: "nvarchar(max)",
                nullable: true,
                oldClrType: typeof(string),
                oldNullable: true);

            migrationBuilder.AddColumn<string>(
                name: "ShipGroupRoomId",
                table: "Ships",
                type: "nvarchar(450)",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "ShipGroupShipTypeId",
                table: "Ships",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "ShipGroupUserId",
                table: "Ships",
                type: "nvarchar(450)",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_Weapons_WeaponGroupUserId_WeaponGroupRoomId_WeaponGroupWeaponTypeId",
                table: "Weapons",
                columns: new[] { "WeaponGroupUserId", "WeaponGroupRoomId", "WeaponGroupWeaponTypeId" });

            migrationBuilder.CreateIndex(
                name: "IX_Ships_ShipGroupUserId_ShipGroupRoomId_ShipGroupShipTypeId",
                table: "Ships",
                columns: new[] { "ShipGroupUserId", "ShipGroupRoomId", "ShipGroupShipTypeId" });

            migrationBuilder.AddForeignKey(
                name: "FK_Ships_ShipGroups_ShipGroupUserId_ShipGroupRoomId_ShipGroupShipTypeId",
                table: "Ships",
                columns: new[] { "ShipGroupUserId", "ShipGroupRoomId", "ShipGroupShipTypeId" },
                principalTable: "ShipGroups",
                principalColumns: new[] { "UserId", "RoomId", "ShipTypeId" },
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_Weapons_WeaponGroups_WeaponGroupUserId_WeaponGroupRoomId_WeaponGroupWeaponTypeId",
                table: "Weapons",
                columns: new[] { "WeaponGroupUserId", "WeaponGroupRoomId", "WeaponGroupWeaponTypeId" },
                principalTable: "WeaponGroups",
                principalColumns: new[] { "UserId", "RoomId", "WeaponTypeId" },
                onDelete: ReferentialAction.Restrict);
        }
    }
}
